Output install-packages-26.04.gif

Set FontSize 34
Set Theme "Neon"
Set WindowBar Colorful
Set BorderRadius 20
Set Width 1500
Set Height 850

Type "git clone https://github.com/Quirky1869/Install-Packages-26.04.git"
Enter
Sleep 1s

Type "cd Install-Packages-26.04"
Enter
Sleep 1s

Type "cp -rf scripts/ bin/install /home/$USER"
Enter
Sleep 1s

Type "cd /home/$USER"
Enter
Sleep 1s

Type "chmod u+x scripts/* install"
Enter
Sleep 1s

Type "./install"
Enter
Sleep 3s